//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunnet.Cli.UIBase {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Information {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Information() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sunnet.Cli.UIBase.Information", typeof(Information).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 This assessment is locked. 的本地化字符串。
        /// </summary>
        internal static string Ade_Assessment_Locked {
            get {
                return ResourceManager.GetString("Ade_Assessment_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An assessment with the same language and same name already exists in the system. 的本地化字符串。
        /// </summary>
        internal static string Ade_AssessmentExsited {
            get {
                return ResourceManager.GetString("Ade_AssessmentExsited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot delete this assessment because it contains a measure. 的本地化字符串。
        /// </summary>
        internal static string Ade_CannotDeleteAssessment {
            get {
                return ResourceManager.GetString("Ade_CannotDeleteAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot delete this measure because it contains an item. 的本地化字符串。
        /// </summary>
        internal static string Ade_CannotDeleteMeasure {
            get {
                return ResourceManager.GetString("Ade_CannotDeleteMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An assessment with the same label already exists in the system. 的本地化字符串。
        /// </summary>
        internal static string Ade_SameAssessmentLabel {
            get {
                return ResourceManager.GetString("Ade_SameAssessmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An item with the same label already exists in the system. 的本地化字符串。
        /// </summary>
        internal static string Ade_SameItemLabel {
            get {
                return ResourceManager.GetString("Ade_SameItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A layout with the same name already exists in the system. 的本地化字符串。
        /// </summary>
        internal static string Ade_SameLayoutName {
            get {
                return ResourceManager.GetString("Ade_SameLayoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A measure with the same label already exists in the system. 的本地化字符串。
        /// </summary>
        internal static string Ade_SameMeasureLabel {
            get {
                return ResourceManager.GetString("Ade_SameMeasureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have an assigned community/district. 的本地化字符串。
        /// </summary>
        internal static string Assessment_No_Community {
            get {
                return ResourceManager.GetString("Assessment_No_Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The assessment is not available now, please try later. 的本地化字符串。
        /// </summary>
        internal static string assessment_unavaiable {
            get {
                return ResourceManager.GetString("assessment_unavaiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can not reset the records of previous year. 的本地化字符串。
        /// </summary>
        internal static string Can_Not_Reset_Year {
            get {
                return ResourceManager.GetString("Can_Not_Reset_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Community / District Name error. 的本地化字符串。
        /// </summary>
        internal static string CommunityNameError {
            get {
                return ResourceManager.GetString("CommunityNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Community / District Name has been used. 的本地化字符串。
        /// </summary>
        internal static string CommunityNameHasBeenUsed {
            get {
                return ResourceManager.GetString("CommunityNameHasBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No field is selected to shown. 的本地化字符串。
        /// </summary>
        internal static string DataExport_FieldEmpty {
            get {
                return ResourceManager.GetString("DataExport_FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access database error. Please contact your webmaster (cliengage@uth.tmc.edu). 的本地化字符串。
        /// </summary>
        internal static string DbError {
            get {
                return ResourceManager.GetString("DbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default package already exists. 的本地化字符串。
        /// </summary>
        internal static string DefautlPackage {
            get {
                return ResourceManager.GetString("DefautlPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The default package cannot be deleted. 的本地化字符串。
        /// </summary>
        internal static string DeleteDefaultPackage {
            get {
                return ResourceManager.GetString("DeleteDefaultPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download error. 的本地化字符串。
        /// </summary>
        internal static string DownloadReportError {
            get {
                return ResourceManager.GetString("DownloadReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If check any one of National Accreditation or the U.S.Military is selected on Regulation Entity, the Verified Star Designation will be 4 ★. 的本地化字符串。
        /// </summary>
        internal static string EnableAutoAssign4StarTips {
            get {
                return ResourceManager.GetString("EnableAutoAssign4StarTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not authorized to process the data. 的本地化字符串。
        /// </summary>
        internal static string global_noauthorization {
            get {
                return ResourceManager.GetString("global_noauthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {Entity} has been inactive. 的本地化字符串。
        /// </summary>
        internal static string HasInactive {
            get {
                return ResourceManager.GetString("HasInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This name already exists. 的本地化字符串。
        /// </summary>
        internal static string IsSameName {
            get {
                return ResourceManager.GetString("IsSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no assessment records for current teacher. 的本地化字符串。
        /// </summary>
        internal static string No_Cot_Assessment {
            get {
                return ResourceManager.GetString("No_Cot_Assessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have not finalized the Wave. 的本地化字符串。
        /// </summary>
        internal static string No_COT_Wave {
            get {
                return ResourceManager.GetString("No_COT_Wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no reports existed. 的本地化字符串。
        /// </summary>
        internal static string No_STG_Report {
            get {
                return ResourceManager.GetString("No_STG_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Percentile Rank is invalid for {0} 的本地化字符串。
        /// </summary>
        internal static string NotPercentileRank {
            get {
                return ResourceManager.GetString("NotPercentileRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please log in to CLI Engage before syncing data. 的本地化字符串。
        /// </summary>
        internal static string Offline_Message {
            get {
                return ResourceManager.GetString("Offline_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {StudentNames} is only assigned to this class! Students must be assigned to at least 1 class. 的本地化字符串。
        /// </summary>
        internal static string OnlyOneClass {
            get {
                return ResourceManager.GetString("OnlyOneClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package name already exists. 的本地化字符串。
        /// </summary>
        internal static string PackageSamename {
            get {
                return ResourceManager.GetString("PackageSamename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report is not found. 的本地化字符串。
        /// </summary>
        internal static string Report_Queue_Report_404 {
            get {
                return ResourceManager.GetString("Report_Queue_Report_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report is not ready yet. 的本地化字符串。
        /// </summary>
        internal static string Report_Queue_Report_Not_Ready {
            get {
                return ResourceManager.GetString("Report_Queue_Report_Not_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your report request has been recorded, you will get an email containing a link to the report later. 的本地化字符串。
        /// </summary>
        internal static string Report_Queue_Submitted {
            get {
                return ResourceManager.GetString("Report_Queue_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Another Report Template with the same name already exists! 的本地化字符串。
        /// </summary>
        internal static string ReportTempNameExists {
            get {
                return ResourceManager.GetString("ReportTempNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This name already exists. 的本地化字符串。
        /// </summary>
        internal static string SameName {
            get {
                return ResourceManager.GetString("SameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *The Star is not calculated until all measures are completed.* 的本地化字符串。
        /// </summary>
        internal static string Trs_CalcStar_NeedCompleted {
            get {
                return ResourceManager.GetString("Trs_CalcStar_NeedCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following classes don&apos;t have playground: {0} 的本地化字符串。
        /// </summary>
        internal static string Trs_Playgournd_Blank {
            get {
                return ResourceManager.GetString("Trs_Playgournd_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no class in the school, can not start assessment. 的本地化字符串。
        /// </summary>
        internal static string Trs_School_Has_No_Class {
            get {
                return ResourceManager.GetString("Trs_School_Has_No_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The age of children along with the # of children must be entered on the class management page for class(es): {0}. Please click Edit to continue. 的本地化字符串。
        /// </summary>
        internal static string Trs_TypeOfClassroom_Blank {
            get {
                return ResourceManager.GetString("Trs_TypeOfClassroom_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please upload a file. 的本地化字符串。
        /// </summary>
        internal static string Upload_a_file {
            get {
                return ResourceManager.GetString("Upload_a_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A {Role} with the same first name, last name, and primary email already exists in the community. 的本地化字符串。
        /// </summary>
        internal static string UserExistedInCommunity {
            get {
                return ResourceManager.GetString("UserExistedInCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A {Role} with the same first name, last name, and primary email already exists in CLI Engage.  Do you want to assign now? 的本地化字符串。
        /// </summary>
        internal static string UserExistedInCurrentRole {
            get {
                return ResourceManager.GetString("UserExistedInCurrentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A {Role} with the same first name, last name, and primary email already exists in the school. 的本地化字符串。
        /// </summary>
        internal static string UserExistedInSchool {
            get {
                return ResourceManager.GetString("UserExistedInSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A {Role} with the same first name, last name, and primary email already exists. 的本地化字符串。
        /// </summary>
        internal static string UserExistedInStatewide {
            get {
                return ResourceManager.GetString("UserExistedInStatewide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A {Role} with the same first name, last name, and primary email already exists in CLI Engage.  Do you want to continue? 的本地化字符串。
        /// </summary>
        internal static string UserExistedInSystem {
            get {
                return ResourceManager.GetString("UserExistedInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A {Role} with the same first name, last name, and primary email already exists in CLI Engage. Do you want to send him/her an invitation? 的本地化字符串。
        /// </summary>
        internal static string UserExistedInSystemSendEmail {
            get {
                return ResourceManager.GetString("UserExistedInSystemSendEmail", resourceCulture);
            }
        }
    }
}
